openapi: 3.0.1
info:
  title: API Example
  description: API Example Description
  version: 1.0.0
paths:
  /tags:
    get:
      summary: Get all tags
      responses:
        '200':
          description: A list of tags
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
components:
  schemas:
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        lang:
          type: string
        usageCount:
          type: integer
          format: int32
